# Generated by Django 5.2.7 on 2025-10-27 18:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendado'), ('IN_PROGRESS', 'Em andamento'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='SCHEDULED', max_length=20)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='clubs.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='clubs.team')),
                ('league_division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='leagues.leaguedivision')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['-date'],
            },
        ),
    ]
