# Generated by Django 5.2.7 on 2025-10-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
