# Generated by Django 5.2.7 on 2025-10-27 17:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('league_division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='leagues.leaguedivision')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
