# Generated by Django 5.2.7 on 2025-10-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedivision',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
