# Generated by Django 5.2.7 on 2025-10-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_leaguedivision_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.RemoveField(
            model_name='team',
            name='short_name',
        ),
    ]
