# Generated by Django 5.2.7 on 2025-10-27 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_leaguedivision_id_alter_team_id'),
        ('leagues', '0003_leaguedivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='leagues.leaguedivision'),
        ),
        migrations.DeleteModel(
            name='LeagueDivision',
        ),
    ]
